#!/usr/bin/env bash

DOTFILES_ROOT="`pwd`"

set -e
echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

setup_gitconfig () {
  if ! [ -f $HOME/.gitconfig ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" tpl/gitconfig > symlinks/gitconfig

    success 'gitconfig'
  fi
}

install_fish() {
  source="$HOME/.terminator/fish"
  dest="$HOME/.config/fish"
  if [ -f $dest ] || [ -d $dest ]
  then
    user "Fish config already found ($dest), overwrite? (Y/N)"
    overwrite=false
    read -n 1 action

      case "$action" in
        y )
          overwrite=true;;
        Y )
          overwrite=true;;
        * )
          overwrite=false;;
      esac

    if [ "$overwrite" == "true" ]
    then
      rm -rf $dest
      ln -s $source $dest
      success "linked $dest"
    else
      user "Skipped this Fish config"
    fi
  else
    mkdir -p $dest
    ln -s $source $dest
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT/symlinks/* -maxdepth 1`
  do
    dest="$HOME/.`basename \"${source}\"`"
    echo $dest

    if [ -f $dest ] || [ -d $dest ]
    then
      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $source $dest
      else
        success "skipped $source"
      fi

    else
      info 'link'
      link_files $source $dest
    fi

  done
}

setup_gitconfig
install_fish
install_dotfiles

echo ''
echo '  All installed!'
